# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Run Test

on:
  push:
    branches: 
    - main
    - develop
  pull_request:
    branches:
    - feature/**
    
jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Start xcode build 🛠
      run: |
        xcodebuild clean test -project coupleDayProject.xcodeproj \
        -scheme coupleDayProject \
        -destination 'platform=iOS Simulator,name=iPhone 13,OS=16.2'
